batch_size: 128
checkpoint_path: SavedModels\lorenz\largerDt_10ks4\best_checkpoint.ckpt
config: configs\Lorenz.yaml
context_length: 4
data_samples: 10000
dataset: custom:lorenz
device: cuda:0
diffusion_config: diffusion_s4
dt: 0.05
eval_every: 50
freq: H
gradient_clip_val: 0.5
init_skip: false
lr: 0.001
max_epochs: 250
model: unconditional
num_batches_per_epoch: 100
num_samples: 16
observation_dim: 3
out_dir: ./
prediction_length: 2
q: 0.0
r: 0.0
sampler: ddpm
sampler_params:
  guidance: quantile
  scale: 2
setup: forecasting
