model: unconditional
diffusion_config: diffusion_s5_large #s5, s4, or unet
observation_dim: 3
dataset: custom:xdsinindependent
freq: H
context_length: 40
prediction_length: 20
dt: .25
data_samples: 10000
lr: 1.e-3
q: 0.0
r: 0.0 
init_skip: False
gradient_clip_val: 0.5
max_epochs: 250
num_batches_per_epoch: 100
batch_size: 128

num_samples: 16
sampler: ddpm
sampler_params:
  guidance: quantile
  scale: 2
eval_every: 50
device: cuda:0 # "cuda:0" for windows, "mps" for mac ONLY FOR TRAINING(breaks during forecasts), "cpu" for default
setup: forecasting
checkpoint_path: 
#checkpoint_path: /Users/monicastudent/Downloads/Continual_TSDiff/lightning_logs/version_7/best_checkpoint.ckpt
